Repository Team-Bob7/AirViewer2-master, pull requests merged in 2022-04, with the labels that each got.

#17 Added a class with mergePDF functionality.
  src/main/java/edu/wright/airviewer2/MergePDFs.java
Labels: enhancement

#26 Added "Merge PDF button for the user.
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
  src/main/resources/edu/wright/airviewer2/AIRFXMLDocument.fxml
Labels: enhancement

#27 Added a test cases to merge the PDFs.
  Test Cases/TestMergePDFs.java
Labels: Test Case

#28 One PDF can be Split into many PDFs
  src/main/java/edu/wright/airviewer2/split.java
Labels: enhancement

#29 The Code as Tested through the Junit.
  Test Cases/splitTest.java
Labels: Test Case

#30 The Button is added to the controller.
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
Labels: enhancement

#31 To the given PDF number of blank pages are added
  src/main/java/edu/wright/airviewer2/AddPages.java
Labels: UserStory

#32 The code is texted through the Junit
  Test Cases/AddPagesTest.java
Labels: UserStory-4(Task)

#33 The UI Button is Added to the controller.
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
Labels: UserStory-4(Task)

#34 The button is added to AddPages
  src/main/resources/edu/wright/airviewer2/AIRFXMLDocument.fxml
Labels: UserStory-4(Task)

#35 The button is added to split PDF
  src/main/resources/edu/wright/airviewer2/AIRFXMLDocument.fxml
Labels: enhancement

#36 The UI button for Split PDF
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
Labels: enhancement

#37 The UI button for Merge PDF
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
Labels: enhancement

#38 The UI button for AddPages
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
Labels: enhancement

#39 Adding content to the PDF.
  src/main/java/edu/wright/airviewer2/AddingContent.java
Labels: UserStory

#40 The code as tested through Junit
  Test Cases/AddingContentTest.java
Labels: Test Case

#41 UI button for Adding Content to the PDF.
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
Labels: enhancement

#42 The UI button for Adding Content.
  src/main/resources/edu/wright/airviewer2/AIRFXMLDocument.fxml
Labels: enhancement

#43 Generating documentation from annotated java
  Deoxygen
Labels: documentation

#44 Delete Deoxygen
  Deoxygen
Labels: documentation

#45 Deoxygen file
  Deoxygen/Sample.md
Labels: documentation

#46 HTML
  Deoxygen/html
Labels: documentation

#47 delete html
  Deoxygen/html
Labels: documentation

#48 Deoxygen file
  Deoxygen/_add_pages_8java.html
  Deoxygen/_adding_content_8java.html
  Deoxygen/_merge_p_d_fs_8java.html
  Deoxygen/annotated.html
  Deoxygen/bc_s.png
  Deoxygen/bdwn.png
  Deoxygen/classedu_1_1wright_1_1airviewer2_1_1_add_pages-members.html
  Deoxygen/classedu_1_1wright_1_1airviewer2_1_1_add_pages.html
  Deoxygen/classedu_1_1wright_1_1airviewer2_1_1_adding_content-members.html
  Deoxygen/classedu_1_1wright_1_1airviewer2_1_1_adding_content.html
  Deoxygen/classedu_1_1wright_1_1airviewer2_1_1_merge_p_d_fs-members.html
  Deoxygen/classedu_1_1wright_1_1airviewer2_1_1_merge_p_d_fs.html
  Deoxygen/classedu_1_1wright_1_1airviewer2_1_1split-members.html
  Deoxygen/classedu_1_1wright_1_1airviewer2_1_1split.html
  Deoxygen/classes.html
  Deoxygen/closed.png
  Deoxygen/doc.png
  Deoxygen/doxygen.css
  Deoxygen/doxygen.svg
  Deoxygen/dynsections.js
  Deoxygen/files.html
  Deoxygen/folderclosed.png
  Deoxygen/folderopen.png
  Deoxygen/functions.html
  Deoxygen/functions_func.html
  Deoxygen/index.html
  Deoxygen/jquery.js
  Deoxygen/menu.js
  Deoxygen/menudata.js
  Deoxygen/namespaceedu_1_1wright_1_1airviewer2.html
  Deoxygen/namespaces.html
  Deoxygen/nav_f.png
  Deoxygen/nav_g.png
  Deoxygen/nav_h.png
  Deoxygen/open.png
  Deoxygen/split_8java.html
  Deoxygen/splitbar.png
  Deoxygen/sync_off.png
  Deoxygen/sync_on.png
  Deoxygen/tab_a.png
  Deoxygen/tab_b.png
  Deoxygen/tab_h.png
  Deoxygen/tab_s.png
  Deoxygen/tabs.css
Labels: documentation

#49 Delete
  Deoxygen/Sample.md
  Deoxygen/_add_pages_8java.html
  Deoxygen/_adding_content_8java.html
  Deoxygen/_merge_p_d_fs_8java.html
  Deoxygen/annotated.html
  Deoxygen/bc_s.png
  Deoxygen/bdwn.png
  Deoxygen/classedu_1_1wright_1_1airviewer2_1_1_add_pages-members.html
  Deoxygen/classedu_1_1wright_1_1airviewer2_1_1_add_pages.html
  Deoxygen/classedu_1_1wright_1_1airviewer2_1_1_adding_content-members.html
  Deoxygen/classedu_1_1wright_1_1airviewer2_1_1_adding_content.html
  Deoxygen/classedu_1_1wright_1_1airviewer2_1_1_merge_p_d_fs-members.html
  Deoxygen/classedu_1_1wright_1_1airviewer2_1_1_merge_p_d_fs.html
  Deoxygen/classedu_1_1wright_1_1airviewer2_1_1split-members.html
  Deoxygen/classedu_1_1wright_1_1airviewer2_1_1split.html
  Deoxygen/classes.html
  Deoxygen/closed.png
  Deoxygen/doc.png
  Deoxygen/doxygen.css
  Deoxygen/doxygen.svg
  Deoxygen/dynsections.js
  Deoxygen/files.html
  Deoxygen/folderclosed.png
  Deoxygen/folderopen.png
  Deoxygen/functions.html
  Deoxygen/functions_func.html
  Deoxygen/index.html
  Deoxygen/jquery.js
  Deoxygen/menu.js
  Deoxygen/menudata.js
  Deoxygen/namespaceedu_1_1wright_1_1airviewer2.html
  Deoxygen/namespaces.html
  Deoxygen/nav_f.png
  Deoxygen/nav_g.png
  Deoxygen/nav_h.png
  Deoxygen/open.png
  Deoxygen/split_8java.html
  Deoxygen/splitbar.png
  Deoxygen/sync_off.png
  Deoxygen/sync_on.png
  Deoxygen/tab_a.png
  Deoxygen/tab_b.png
  Deoxygen/tab_h.png
  Deoxygen/tab_s.png
  Deoxygen/tabs.css
Labels: documentation

#50 Deoxygen file
  Deoxygen/Sample.md
Labels: documentation

#52 Program By Contract
  Program By Contract
Labels: documentation

#53 Product Backlog Items
  Product Backlog Items
Labels: documentation

#54 Software Design Document (SDD)
  Software Design Document (SDD)
Labels: documentation

#55 Code Coverage through Junit
  Code Coverage/Sample.md
Labels: documentation

#56 Code Coverage through Junit
  Code Coverage/Code Coverage/AddPagesTest.java
  Code Coverage/Code Coverage/AddingContentTest.java
  Code Coverage/Code Coverage/TestMergePDFs.java
  Code Coverage/Code Coverage/splitTest.java
Labels: documentation
